export const GET = "GET";
export const UPDATE_GUILD_ADD_GUILD_MEMBER = "UPDATE_GUILD_ADD_GUILD_MEMBER";
export const UPDATE_GUILD_REMOVE_GUILD_MEMBER = "UPDATE_GUILD_REMOVE_GUILD_MEMBER";
export const UPDATE_GUILD_EDIT_GUILD_MEMBER = "UPDATE_GUILD_EDIT_GUILD_MEMBER";