export const ADD_FILTER = "ADD_FILTER";
export const REMOVE_FILTER = "REMOVE_FILTER";

export const UPDATE_SEARCH_START_SEARCH = "UPDATE_SEARCH_START_SEARCH";
export const UPDATE_SEARCH_CANCEL_SEARCH = "UPDATE_SEARCH_CANCEL_SEARCH";
export const UPDATE_SEARCH_EXPAND_SEARCH = "UPDATE_SEARCH_EXPAND_SEARCH";