export const ADD_FILTER: string = "ADD_FILTER";
export const REMOVE_FILTER: string = "REMOVE_FILTER";

export const UPDATE_SEARCH_START_SEARCH: string = "UPDATE_SEARCH_START_SEARCH";
export const UPDATE_SEARCH_CANCEL_SEARCH: string = "UPDATE_SEARCH_CANCEL_SEARCH";
export const UPDATE_SEARCH_EXPAND_SEARCH: string = "UPDATE_SEARCH_EXPAND_SEARCH";